# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f15967edc488f9d2e83467f672835d1b96bf4a20333cb823e6b9aea0c01011cd3a385821cf1233f681c05ccc8e0a83d6a06a77184a0c0462dd6c0dd55a9a0fb9

test:
  secret_key_base: 62d53f7233fc2f6aaf07f60b952fa8a0e5742dd90c6aed22594ff82b0e9e4c9781c3e12d3d290e11476d2837fa7d70d47c1ecd888aab3d337ca5287e398599b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
